<a href="https://colab.research.google.com/github/hasi-b/ML-Python-Practices/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np

######BASIC##########

a = np.array([1,2,3]) #1d array
print(a)
b = np.array([[4.2,3.2,5.2],[5.1,4.6,8.4]])
print(b)
ND= a.ndim #number of dimensions
print("Number of dimensions of A is {}".format(ND))
ND = b.ndim #number of dimensions
print("Number of dimensions of B is "+ str(ND)) #casting int ND to string
a.shape #shape of array
b.shape #shape of array
print("data type of a "+ str(a.dtype))
print("data type of b "+str(b.dtype))
print("size of a "+str(a.size))
print("size of b "+str(b.size))
print("size of each item of a "+str(a.itemsize))
print("size of each item of b "+str(b.itemsize))
print("size of total array a "+str(a.nbytes)) ## a.itemsize*a.size
print("size of total array b "+str(b.nbytes)) ## b.itemsize*b.size

########ACCESSING CHANGING COLUMNS##########



[1 2 3]
[[4.2 3.2 5.2]
 [5.1 4.6 8.4]]
Number of dimensions of A is 1
Number of dimensions of B is 2
data type of a int64
data type of b float64
size of a 3
size of b 6
size of each item of a 8
size of each item of b 8
size of total array a 24
size of total array b 48
